# Generated by Django 3.2.25 on 2024-06-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_project',
            name='status',
        ),
    ]
