# Generated by Django 3.2.25 on 2024-06-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_remove_create_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='algorithmandblockdiagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='datasets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='resultanlysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='statusofpaper',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='suggesionsonpreviouspreviousreview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
